### ISSUE TITLE
Lavender attachment will not comect 

### ISSUE THREAD

**Issue by Spikeiy** [Achimobil/FS22_John_Deere_CS_690_lavender#2]
Error message is attaching not allowed for the John deere cs 690 on Playstation 4 farming simulator 22 digital version

**Comment by Achimobil** [comment]
You can only attach the Lavender header to the lavernder version of the JD. 
When you have done that please make sceens and logs to check the error deeper

**Comment by Spikeiy** [comment]
![Uploading 20240207_163518.jpg…]()

**Comment by Spikeiy** [comment]
![20240207_163335](https://github.com/Achimobil/FS22_John_Deere_CS_690_lavender/assets/159197439/e2d621ca-0299-4b8a-9bc3-d3511261a9cd)

**Comment by Achimobil** [comment]
I think the upload is broken, could not get and view it

**Comment by Spikeiy** [comment]
![20240207_163335](https://github.com/Achimobil/FS22_John_Deere_CS_690_lavender/assets/159197439/52cc5b27-70ff-4796-a1b1-c893257a4fb7)
![20240207_163518](https://github.com/Achimobil/FS22_John_Deere_CS_690_lavender/assets/159197439/8efe71f2-168a-43a5-a565-1462568a508d)

**Comment by Achimobil** [comment]
I will check this on PC soon if this is reproducable

**Comment by Achimobil** [comment]
I checked this and I could connect both headers without problems.
That us why I ask for a log file. You are using the Harvester on a map where no Lavender is available.
Only then you could not connect the header to the Harvester.

If you are using the Harvester on a map with lavender, please let me know which map it is, then reopen the ticket and I will check it again on that map, but I assume that you do not have Lavender where you are. The Harvester do not add lavender to a map and is only usable on maps where lavender is available. Like these ones:

- https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=269035&title=fs2022
- https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=267424&title=fs2022
- https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=269039&title=fs2022

**Comment by Spikeiy** [comment]
Which maps have lavender

**Comment by Achimobil** [comment]
I put three links with such maps in my comment. Please read the comment complete ;)
