### ISSUE TITLE
Lavendel XML

### ISSUE THREAD

**Issue by nthrlx** [Achimobil/FS22_John_Deere_CS_690_lavender#3]
Hey,

erst mal sorry, ich bin neu hier und noch nicht ganz sicher wie github verwendet werden soll. :3 Und tut mir leid für die etwas banale Angelegenheit.

Also nochmal zu meiner Frage:

Ich hatte die Lavendel Dateien tatsächlich auch aus der NF Marsch, aber bekomme es einfach nicht hin das Ganze so realistisch aussehen zu lassen. 
Könntest du u.U. erklären welche Parameter du wie angepasst hast? Oder ggf. die Lavendel Dateien veröffentlichen? Ich denke da würden sich einige Leute freuen :) 

Beste Grüße
Alex

**Comment by Achimobil** [comment]
Kein ding, wir haben alle mal angefangen mit GitHub.

Leider habe ich die Dateien von damals nicht mehr. 
Ich werde da bestimmt mal ein tut video zu machen wie man das richtig einstellt, aber aktuell fehlt mir dafür die Zeit.
Ich weiß aber noch wo ich ws gemacht habe. Da gibt es eine lavender.xml die müsste in FS22_NF_Marsch_4fach\maps\foliage\lavender zu finden sein. Darin hatte ich mit numBlocksPerheightVariance und Unit, width, height, widthVariance, horizontalPositionVariance so lange rum gespielt, bis das gut aus sah

**Comment by nthrlx** [comment]
Achso, ja die Lavender.xml ist auch die Datei in der ich das ganze probiere.  Mal schaun, vllt bekomm ichs ja noch hin.

Trotzdem danke dir! :)
